# Generated by Django 4.2.2 on 2023-06-24 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Only Latin letters and digits are allowed.",
                                regex="^[a-zA-Z0-9]+$",
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("homepage", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "text",
                    models.TextField(
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Only <a>, <code>, <i>, and <strong> tags are allowed.",
                                regex="^<(a|code|i|strong)>(.*?)<\\/(a|code|i|strong)>$",
                            )
                        ]
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
